const leaderboard = [{
    id: 1,
    name: "Super Mario 64",
    platforms: [
        "N64", "VC", "EMU"
    ],

    category: ["120 Star", "70 Star", "16 Star", "1 Star", "0 Star"],

    leaderboardTimes: [{
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Suigi",
        fullTime: 13528,
        category: "120 Star",
        hour: 1,
        minutes: 35,
        seconds: 28,
        date: "1 month",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "Weegee",
        fullTime: 13602,
        category: "120 Star",
        hour: 1,
        minutes: 36,
        seconds: "02",
        date: "5 months",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    }, {
        player: "HorrorDoesSpeedruns",
        fullTime: 13913,
        category: "120 Star",
        hour: 1,
        minutes: 39,
        seconds: 13,
        date: "7 days",
        version: "Japan",
        platform: "N64",
        verified: true,
    },]
}];

export default leaderboard;